name: anuj_kumar
description: A new Jaspr project
version: 0.0.1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  jaspr: ^0.22.0
  jaspr_router: ^0.8.0
  jaspr_lucide: ^0.20.0

dev_dependencies:
  build_runner: ^2.6.0
  jaspr_web_compilers: ^4.3.2+1
  jaspr_builder: ^0.22.0
  jaspr_lints: ^0.5.1
  lints: ^5.0.0
  jaspr_tailwind: ^0.3.5

jaspr:
  mode: static

